AWSTemplateFormatVersion: 2010-09-09
Description: >-
  tech-challenge-sthima

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        APIKEY: 925eba28
        MOVIESTABLE: !Ref TableMovies
        MOVIESTABLE_HASHKEY: movieItemType
        MOVIESTABLE_SORTKEY: movieCompositeImdbID
        HASH_MOVIES: movie
        HASH_BOOKMARK: bookmark
        HASH_CACHE: cache
    Layers:
      - !Ref LayerTypescriptDependencies
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 60

Resources:
  APIMovies:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  TableMovies:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "movieItemType"
          AttributeType: "S"
        - AttributeName: "movieCompositeImdbID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "movieItemType"
          KeyType: "HASH"
        - AttributeName: "movieCompositeImdbID"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  LayerTypescriptDependencies:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      Description: Common runtime dependencies for Lambdas (public and private packages).
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain

  FunctionSearchMovies:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/src/functions/SearchMovies.SearchMovies
      Description: A function that searches for a movie from the given string.
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableMovies
        - DynamoDBWritePolicy:
            TableName: !Ref TableMovies
        - AWSLambdaRole
      Environment:
        Variables:
          CACHE_FUNCTION: !Ref FunctionCacheImdbSearch
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref APIMovies
            Path: /movie/search
            Method: POST

  FunctionCacheImdbSearch:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/src/functions/CacheImdbSearch.CacheImdbSearch
      Description: A function that caches searches made at IMDB API.
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref TableMovies

  FunctionBookmarkAddMovie:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/src/functions/BookmarkAddMovie.BookmarkAddMovie
      Description: A function that bookmarks a movie from the given imdbID.
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref TableMovies
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref APIMovies
            Path: /bookmark/{imdbID}
            Method: POST

  FunctionBookmarkRemoveMovie:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/src/functions/BookmarkRemoveMovie.BookmarkRemoveMovie
      Description: A function that removes a bookmark from the given imdbID.
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref TableMovies
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref APIMovies
            Path: /bookmark/{imdbID}
            Method: DELETE

  FunctionListBookmarkedMovies:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/src/functions/ListBookmarkedMovies.ListBookmarkedMovies
      Description: A function that lists bookmarked movies.
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TableMovies
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref APIMovies
            Path: /bookmark
            Method: GET
